In [15]:
import math
import numpy as np

In [11]:
f = lambda x: 1.75199326e-06 * math.exp(-3.79829049e+03 * x)

In [ ]:
f = lambda x: 1.75199326e-06 * math.exp(3.79829049e+03 * x)

In [5]:
 a = 1.75199326 * math.exp(math.log(1e-06))
 a

1.7519932600000009e-06

In [8]:
-3.79829049e+03 * math.log(1e-03)

26237.661183405147

In [16]:
x_mid = np.array(range(0, 24, 1)) * 0.05

In [21]:
f = lambda a, b, x: np.array(a) @ np.exp( - x * np.array(b))


"""
  0.0016801321866205532
[2.08404657e+00 4.57120604e-12 4.25673560e-01]
[4.60646509 0.51699632 1.85283244]
1

0.0016801321866264374
[2.08404657 0.42567356]
[4.60646509 1.85283244]
1

0.0016801321866166674
[6.68499642e-11 1.75199326e-06 2.08404657e+00 4.25673560e-01]
[3.92780507e+00 3.79829049e+03 4.60646509e+00 1.85283244e+00]
"""

'\n  0.0016801321866205532\n[2.08404657e+00 4.57120604e-12 4.25673560e-01]\n[4.60646509 0.51699632 1.85283244]\n1\n\n0.0016801321866264374\n[2.08404657 0.42567356]\n[4.60646509 1.85283244]\n1\n\n0.0016801321866166674\n[6.68499642e-11 1.75199326e-06 2.08404657e+00 4.25673560e-01]\n[3.92780507e+00 3.79829049e+03 4.60646509e+00 1.85283244e+00]\n'

In [71]:
f = lambda a, b, x: np.round(np.array(a),4) @ np.exp( - x * np.round(np.array(b), 4))
x_mid = np.array(range(0, 24, 1)) * 0.05
a = [0.0951, 0.8607, 1.5576]
b = [1.0,3.0, 5.0]
a1 = [2.202, 0.305]
b1 = [4.45, 1.58]
a2 = [2.08404657, 0.42567356]
b2 = [4.60646509, 1.85283244]
a3 = [2.08404657e+00, 4.25673560e-01, 4.57120604e-12]
b3 = [4.60646509 ,1.85283244, 0.51699632]
a4 = [6.68499642e-11, 1.75199326e-06, 2.08404657e+00 ,4.25673560e-01]
b4 = [3.92780507e+00, 3.79829049e+03 ,4.60646509e+00, 1.85283244e+00]
[f(a2, b2, x) - f(a3, b3, x) for x in x_mid]
[f(a2, b2, x)- f(a4, b4, x)  for x in x_mid]


[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [67]:
np.max(np.abs([f(a2, b2, x) - f(a3, b3, x) for x in x_mid]))

0.0

In [68]:
np.max(np.abs([f(a2, b2, x)- f(a4, b4, x)  for x in x_mid] ))

0.0

In [72]:
ft = np.array([f(a, b, x) for x in x_mid])
fl = np.array([f(a1, b1, x) for x in x_mid])
f2 = np.array([f(a2, b2, x) for x in x_mid])
f3 = np.array([f(a3, b3, x) for x in x_mid])
f4 = np.array([f(a4, b4, x) for x in x_mid])
print(np.abs(ft - fl).max())
print(np.abs(ft - f2).max())
print(np.abs(ft - f3).max())
print(np.abs(ft - f4).max())

0.006399999999999739
0.0036999999999998145
0.0036999999999998145
0.0036999999999998145


In [63]:
np.linalg.norm(ft - fl), np.linalg.norm(ft - f3)

(0.009741148273458575, 0.004943307312571838)

In [64]:
y_mid = np.array([2.51, 2.04, 1.67, 1.37, 1.12, 0.93, 0.77, 0.64, 0.53, 0.45, 0.38, 0.32, 0.27, 0.23, 0.20, 0.17, 0.15, 0.13, 0.11, 0.10, 0.09,0.08, 0.07, 0.06])


In [73]:
print(np.abs(ft - y_mid).max())
print(np.abs(y_mid - fl).max())
print(np.abs(y_mid - f2).max())


0.004333373291085518
0.006627099861789665
0.0033270793548523248


In [75]:
np.linalg.norm(ft - y_mid)/24, np.linalg.norm(fl - y_mid)/24, np.linalg.norm(f2 - y_mid)/24

(0.0004889469349932542, 0.0005046251575199018, 0.000462396329192439)